version: '2'
services:
    phase1-app:
        image: phase1
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://phase1-mysql:3306/phase1?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    phase1-mysql:
        extends:
            file: mysql.yml
            service: phase1-mysql
